EXAMPLEFORMAT = "\"{text}\""
EXAMPLEFORMAT_SPACE = " \"{text}\""

TASK2LABELSTRINGS = {
    "sentiment2": [
        [   
            "This movie review exhibits a negative bias:",
            "The inclination of this movie review is towards the negative side:",
            "There is a unfavorable slant in this movie review:",
            "The overall tone of this movie review is negative:",
            "This movie review shows a leaning against the subject:",
            "There is a negative inclination in this movie review:",
            "The overall impression of this movie review is pessimistic:",
            "This movie review tends to disfavor the subject being discussed:",
            "There is a negative inclination evident in this movie review:",
            "The general sentiment of this movie review is negative:",
            "This movie review leans negative:"
        ],
        [
            "This movie review exhibits a positive bias:",
            "The inclination of this movie review is towards the positive side:",
            "There is a favorable slant in this movie review:",
            "The overall tone of this movie review is positive:",
            "This movie review shows a leaning in favor of the subject:",
            "There is a positive inclination in this movie review:",
            "The overall impression of this movie review is optimistic:",
            "This movie review tends to favor the subject being discussed:",
            "There is a positive inclination evident in this movie review:",
            "The general sentiment of this movie review is positive:",
            "This movie review leans positive:"
        ]
    ],
        "sentiment2-adv": [
        [   
            "This movie review is meant to trick you but contains a negative bias:",
            "This oddly worded movie review is actually negative:",
            "A negative bias is on display in this deceptive movie review:",
            "This movie review may seem confusing on the surface, but it harbors a negative bias:",
            "In this deceptive movie review, a negative bias is cleverly concealed:",
            "Behind its confusing facade, this movie review conceals a negative bias:",
            "This movie review's misleading nature is overshadowed by its negative bias:",
            "While it may be misleading, this movie review unmistakably carries a negative bias:",
            "This movie review, while misleading, clearly showcases a negative bias:",
            "A negative bias lurks beneath the surface of this deceptive movie review:",
            "While it may not appear so initially, this movie review reveals a negative bias:"
        ],
        [   
            "This movie review is meant to trick you but contains a positive bias:",
            "This oddly worded movie review is actually positive:",
            "A positive bias is on display in this deceptive movie review:",
            "This movie review may seem confusing on the surface, but it harbors a positive bias:",
            "In this deceptive movie review, a positive bias is cleverly concealed:",
            "Behind its confusing facade, this movie review conceals a positive bias:",
            "This movie review's misleading nature is overshadowed by its positive bias:",
            "While it may be misleading, this movie review unmistakably carries a positive bias:",
            "This movie review, while misleading, clearly showcases a positive bias:",
            "A positive bias lurks beneath the surface of this deceptive movie review:",
            "While it may not appear so initially, this movie review reveals a positive bias:"
        ]
    ],
    # "sentiment2-adv": [
    #     [   
    #         "This misleading movie review exhibits a negative bias:",
    #         "This seemingly positive movie review is actually negative:",
    #         "A negative bias is on display in this deceptive movie review:",
    #         "This movie review may seem positive on the surface, but it harbors a negative bias:",
    #         "In this deceptive movie review, a negative bias is cleverly concealed:",
    #         "Behind its facade of positivity, this movie review conceals a negative bias:",
    #         "This movie review's misleading nature is overshadowed by its negative bias:",
    #         "While it may be misleading, this movie review unmistakably carries a negative bias:",
    #         "This movie review, while misleading, clearly showcases a negative bias:",
    #         "A negative bias lurks beneath the surface of this seemingly positive movie review:",
    #         "While it may appear positive initially, this movie review reveals a negative bias:"
    #     ],
    #     [   
    #         "This misleading movie review exhibits a positive bias:",
    #         "This seemingly negative movie review is actually positive:",
    #         "A positive bias is on display in this deceptive movie review:",
    #         "This movie review may seem negative on the surface, but it harbors a positive bias:",
    #         "In this deceptive movie review, a positive bias is cleverly concealed:",
    #         "Behind its facade of negativity, this movie review conceals a positive bias:",
    #         "This movie review's misleading nature is overshadowed by its positive bias:",
    #         "While it may be misleading, this movie review unmistakably carries a positive bias:",
    #         "This movie review, while misleading, clearly showcases a positive bias:",
    #         "A positive bias lurks beneath the surface of this seemingly negative movie review:",
    #         "While it may appear negative initially, this movie review reveals a positive bias:"
    #     ]
    # ],
    "sentiment2-advmix": [
        [   
            "This movie review exhibits a negative bias:",
            "The inclination of this movie review is towards the negative side:",
            "There is a unfavorable slant in this movie review:",
            "The overall tone of this movie review is negative:",
            "This movie review shows a leaning against the subject:",
            "There is a negative inclination in this movie review:",
            "This misleading movie review exhibits a negative bias:",
            "This seemingly positive movie review is actually negative:",
            "A negative bias is on display in this deceptive movie review:",
            "This movie review may seem positive on the surface, but it harbors a negative bias:",
            "In this deceptive movie review, a negative bias is cleverly concealed:"
        ],
        [
            "This movie review exhibits a positive bias:",
            "The inclination of this movie review is towards the positive side:",
            "There is a favorable slant in this movie review:",
            "The overall tone of this movie review is positive:",
            "This movie review shows a leaning in favor of the subject:",
            "There is a positive inclination in this movie review:",
            "This misleading movie review exhibits a positive bias:",
            "This seemingly negative movie review is actually positive:",
            "A positive bias is on display in this deceptive movie review:",
            "This movie review may seem negative on the surface, but it harbors a positive bias:",
            "In this deceptive movie review, a positive bias is cleverly concealed:"
        ]
    ],
    "sentiment2-mr": [
        [   
            "This RottenTomatoes review exhibits a negative bias:",
            "The inclination of this RottenTomatoes review is towards the negative side:",
            "There is a unfavorable slant in this RottenTomatoes review:",
            "The overall tone of this RottenTomatoes review is negative:",
            "This RottenTomatoes review shows a leaning against the subject:",
            "There is a negative inclination in this RottenTomatoes review:",
            "The overall impression of this RottenTomatoes review is pessimistic:",
            "This RottenTomatoes review tends to disfavor the subject being discussed:",
            "There is a negative inclination evident in this RottenTomatoes review:",
            "The general sentiment of this RottenTomatoes review is negative:",
            "This RottenTomatoes review leans negative:"
        ],
        [
            "This RottenTomatoes review exhibits a positive bias:",
            "The inclination of this RottenTomatoes review is towards the positive side:",
            "There is a favorable slant in this RottenTomatoes review:",
            "The overall tone of this RottenTomatoes review is positive:",
            "This RottenTomatoes review shows a leaning in favor of the subject:",
            "There is a positive inclination in this RottenTomatoes review:",
            "The overall impression of this RottenTomatoes review is optimistic:",
            "This RottenTomatoes review tends to favor the subject being discussed:",
            "There is a positive inclination evident in this RottenTomatoes review:",
            "The general sentiment of this RottenTomatoes review is positive:",
            "This RottenTomatoes review leans positive:"
        ]
    ],
    "sentiment2-cr": [
        [   
            "This customer review exhibits a negative bias:",
            "The inclination of this customer review is towards the negative side:",
            "There is a unfavorable slant in this customer review:",
            "The overall tone of this customer review is negative:",
            "This customer review shows a leaning against the subject:",
            "There is a negative inclination in this customer review:",
            "The overall impression of this customer review is pessimistic:",
            "This customer review tends to disfavor the subject being discussed:",
            "There is a negative inclination evident in this customer review:",
            "The general sentiment of this customer review is negative:",
            "This customer review leans negative:"
        ],
        [
            "This customer review exhibits a positive bias:",
            "The inclination of this customer review is towards the positive side:",
            "There is a favorable slant in this customer review:",
            "The overall tone of this customer review is positive:",
            "This customer review shows a leaning in favor of the subject:",
            "There is a positive inclination in this customer review:",
            "The overall impression of this customer review is optimistic:",
            "This customer review tends to favor the subject being discussed:",
            "There is a positive inclination evident in this customer review:",
            "The general sentiment of this customer review is positive:",
            "This customer review leans positive:"
        ]
    ],
    "sentiment2-amazon": [
        [   
            "This Amazon review exhibits a negative bias:",
            "The inclination of this Amazon review is towards the negative side:",
            "There is a unfavorable slant in this Amazon review:",
            "The overall tone of this Amazon review is negative:",
            "This Amazon review shows a leaning against the subject:",
            "There is a negative inclination in this Amazon review:",
            "The overall impression of this Amazon review is pessimistic:",
            "This Amazon review tends to disfavor the subject being discussed:",
            "There is a negative inclination evident in this Amazon review:",
            "The general sentiment of this Amazon review is negative:",
            "This Amazon review leans negative:"
        ],
        [
            "This Amazon review exhibits a positive bias:",
            "The inclination of this Amazon review is towards the positive side:",
            "There is a favorable slant in this Amazon review:",
            "The overall tone of this Amazon review is positive:",
            "This Amazon review shows a leaning in favor of the subject:",
            "There is a positive inclination in this Amazon review:",
            "The overall impression of this Amazon review is optimistic:",
            "This Amazon review tends to favor the subject being discussed:",
            "There is a positive inclination evident in this Amazon review:",
            "The general sentiment of this Amazon review is positive:",
            "This Amazon review leans positive:"
        ]
    ],
    "sentiment2-yelp": [
        [   
            "This Yelp review exhibits a negative bias:",
            "The inclination of this Yelp review is towards the negative side:",
            "There is a unfavorable slant in this Yelp review:",
            "The overall tone of this Yelp review is negative:",
            "This Yelp review shows a leaning against the subject:",
            "There is a negative inclination in this Yelp review:",
            "The overall impression of this Yelp review is pessimistic:",
            "This Yelp review tends to disfavor the subject being discussed:",
            "There is a negative inclination evident in this Yelp review:",
            "The general sentiment of this Yelp review is negative:",
            "This Yelp review leans negative:"
        ],
        [
            "This Yelp review exhibits a positive bias:",
            "The inclination of this Yelp review is towards the positive side:",
            "There is a favorable slant in this Yelp review:",
            "The overall tone of this Yelp review is positive:",
            "This Yelp review shows a leaning in favor of the subject:",
            "There is a positive inclination in this Yelp review:",
            "The overall impression of this Yelp review is optimistic:",
            "This Yelp review tends to favor the subject being discussed:",
            "There is a positive inclination evident in this Yelp review:",
            "The general sentiment of this Yelp review is positive:",
            "This Yelp review leans positive:"
        ]
    ],
    "poemsentiment2": [
        [
            "This poem's verse has a negative tone:",
            "The verse of this poem embodies a negative tone:",
            "A pessimistic sentiment lingers in this poem's verse:",
            "This poem's verse exudes a dark and gloomy atmosphere:",
            "The tone of this poem's verse leans towards negativity:",
            "A sense of despair and sadness permeates the lines of this poem's verse:",
            "The verse of this poem reflects a somber and disheartening mood:",
            "The negative undertone of this poem's verse evokes a melancholic feeling:",
            "The sentiment conveyed by this poem's verse is predominantly negative:",
            "The verse of this poem paints a bleak and desolate picture:",
            "A somber aura envelops the words of this poem's verse:"
        ],
        [
            "This poem's verse has a positive tone:",
            "The verse of this poem radiates a positive tone:",
            "A hopeful and uplifting sentiment permeates this poem's verse:",
            "This poem's verse exudes an optimistic and joyful atmosphere:",
            "The tone of this poem's verse leans towards positivity:",
            "A sense of beauty and inspiration fills the lines of this poem's verse:",
            "The verse of this poem reflects a celebratory and enthusiastic mood:",
            "The positive undertone of this poem's verse evokes a sense of delight:",
            "The sentiment conveyed by this poem's verse is predominantly positive:",
            "The verse of this poem paints a vibrant and uplifting picture:",
            "An uplifting aura envelops the words of this poem's verse:"
        ],
        [
            "This poem's verse has a neutral tone:",
            "The verse of this poem maintains a neutral tone:",
            "A balanced and impartial sentiment characterizes this poem's verse:",
            "This poem's verse conveys a neutral and unbiased atmosphere:",
            "The tone of this poem's verse remains neutral throughout:",
            "A sense of neutrality and objectivity pervades the lines of this poem's verse:",
            "The verse of this poem reflects a calm and detached mood:",
            "The sentiment conveyed by this poem's verse is neither positive nor negative:",
            "The verse of this poem paints a picture devoid of strong emotions:",
            "An atmosphere of neutrality envelops the words of this poem's verse:",
            "The tone of this poem's verse is consistently neutral:"
        ]
    ],
    "finance_sentiment3": [
        [  
            "This financial news excerpt expresses a negative polarity:",
            "This financial news snippet conveys a bearish sentiment:",
            "The tone of this financial news excerpt leans towards the negative:",
            "This financial news segment reflects a pessimistic outlook:",
            "A negative undertone permeates this financial news extract:",
            "The sentiment conveyed by this financial news snippet is predominantly negative:",
            "This financial news passage exudes a downbeat sentiment:",
            "The overall tone of this financial news excerpt is unfavorable:",
            "Negativity prevails in this financial news segment:",
            "This financial news snippet presents a gloomy perspective:",
            "The sentiment expressed in this financial news excerpt is largely negative:"
        ], 
        [   
            "This financial news excerpt expresses no polarity:",
            "This financial news snippet lacks any discernible polarity:",
            "The tone of this financial news excerpt is devoid of any explicit positivity or negativity:",
            "This financial news segment presents information without a clear emotional bias:",
            "No distinct polarity is evident in this financial news extract:",
            "The sentiment conveyed by this financial news snippet is neutral and non-committal:",
            "This financial news passage remains neutral in its presentation:",
            "The overall tone of this financial news excerpt is neither positive nor negative:",
            "This financial news snippet provides an objective account without expressing any polarity:",
            "The sentiment expressed in this financial news excerpt is neutral throughout:",
            "This financial news excerpt maintains a neutral standpoint:"
        ], 
        [   
            "This financial news excerpt expresses a positive polarity:",
            "This financial news snippet exudes a positive sentiment:",
            "The tone of this financial news excerpt leans towards the positive:",
            "This financial news segment reflects an optimistic outlook:",
            "A positive undertone permeates this financial news extract:",
            "The sentiment conveyed by this financial news snippet is predominantly positive:",
            "This financial news passage radiates positivity:",
            "The overall tone of this financial news excerpt is favorable:",
            "Positivity prevails in this financial news segment:",
            "This financial news snippet presents an encouraging perspective:",
            "The sentiment expressed in this financial news excerpt is largely positive:"
        ]
    ],
    "tweet_eval-sentiment": [
        [   
            "This tweet exhibits a negative bias:",
            "The inclination of this tweet is towards the negative side:",
            "There is a unfavorable slant in this tweet:",
            "The overall tone of this tweet is negative:",
            "This tweet shows a leaning against the subject:",
            "There is a negative inclination in this tweet:",
            "The overall impression of this tweet is pessimistic:",
            "This tweet tends to disfavor the subject being discussed:",
            "There is a negative inclination evident in this tweet:",
            "The general sentiment of this tweet is negative:",
            "This tweet leans negative:"
        ],
        [
            "This tweet leans neutral:",
            "The tone of this tweet is impartial:",
            "This tweet remains balanced and neutral:",
            "The overall sentiment of this tweet is neither positive nor negative:",
            "The author takes a neutral stance in this tweet:",
            "This tweet presents a neutral perspective:",
            "The author's viewpoint in this tweet is unbiased and neutral:",
            "This tweet maintains a neutral tone throughout:",
            "The prevailing sentiment in this tweet is one of neutrality:",
            "The author's opinion in this tweet leans towards being neutral:",
            "The tweet reflects a neutral standpoint:"
        ],
        [
            "This tweet exhibits a positive bias:",
            "The inclination of this tweet is towards the positive side:",
            "There is a favorable slant in this tweet:",
            "The overall tone of this tweet is positive:",
            "This tweet shows a leaning in favor of the subject:",
            "There is a positive inclination in this tweet:",
            "The overall impression of this tweet is optimistic:",
            "This tweet tends to favor the subject being discussed:",
            "There is a positive inclination evident in this tweet:",
            "The general sentiment of this tweet is positive:",
            "This tweet leans positive:"
        ],
    ],
    "tweet_eval-hate": [ 
        [
            "This tweet contains benign language:",
            "The language used in this tweet is harmless:",
            "The content of this tweet is respectful:",
            "This tweet uses inoffensive language:",
            "The wording in this tweet is benign:",
            "The language in this tweet poses no harm:",
            "This tweet employs non-threatening language:",
            "The text within this tweet is free from controversy:",
            "The language used in this tweet is innocuous:",
            "This tweet consists of safe and non-controversial language:",
            "The content of this tweet is free from offense:"
        ],
        [
            "This tweet contains hateful language:",
            "The language used in this tweet is offensive:",
            "The content of this tweet is disrespectful:",
            "This tweet uses objectionable language:",
            "The wording in this tweet is inappropriate:",
            "The language in this tweet is harmful:",
            "This tweet employs offensive language:",
            "The text within this tweet is offensive and controversial:",
            "The language used in this tweet is objectionable:",
            "This tweet consists of offensive and inappropriate language:",
            "The content of this tweet is disrespectful and harmful:"
        ],
    ],
    "sentiment5":[
        [
            "This movie review leans very negative:",
            "The tone of this movie review is overwhelmingly negative:",
            "This movie review is heavily skewed towards the negative side:",
            "The overall sentiment of this movie review is predominantly negative:",
            "The negative perspective of this movie review is quite pronounced:",
            "There is a strong inclination towards negativity in this movie review:",
            "The author's viewpoint in this movie review is primarily negative:",
            "This movie review tends to be highly critical and pessimistic:",
            "The prevailing sentiment in this movie review is largely negative:",
            "The author's opinion in this movie review is heavily weighted towards negativity:",
            "The negative stance of this review is quite prominent:"
        ],
        [
            "This movie review leans somewhat negative:",
            "The tone of this movie review is moderately negative:",
            "This movie review has a slight inclination towards the negative side:",
            "The overall sentiment of this movie review is somewhat negative:",
            "The negative perspective of this movie review is somewhat apparent:",
            "There is a mild inclination towards negativity in this movie review:",
            "The author's viewpoint in this movie review is somewhat negative:",
            "This movie review tends to be moderately critical and pessimistic:",
            "The prevailing sentiment in this movie review is somewhat negative:",
            "The author's opinion in this movie review leans slightly towards negativity:",
            "The negative stance of this review is somewhat evident:"
        ],
        [
            "This movie review leans neutral:",
            "The tone of this movie review is impartial:",
            "This movie review remains balanced and neutral:",
            "The overall sentiment of this movie review is neither positive nor negative:",
            "The author takes a neutral stance in this movie review:",
            "This movie review presents a neutral perspective:",
            "The author's viewpoint in this movie review is unbiased and neutral:",
            "This movie review maintains a neutral tone throughout:",
            "The prevailing sentiment in this movie review is one of neutrality:",
            "The author's opinion in this movie review leans towards being neutral:",
            "The review reflects a neutral standpoint:"
        ],
        [
            "This movie review leans somewhat positive:",
            "The tone of this movie review is moderately positive:",
            "This movie review has a slight inclination towards the positive side:",
            "The overall sentiment of this movie review is somewhat positive:",
            "The positive perspective of this movie review is somewhat apparent:",
            "There is a mild inclination towards positivity in this movie review:",
            "The author's viewpoint in this movie review is somewhat positive:",
            "This movie review tends to be moderately optimistic and favorable:",
            "The prevailing sentiment in this movie review is somewhat positive:",
            "The author's opinion in this movie review leans slightly towards positivity:",
            "The positive stance of this review is somewhat evident:"
        ],
        [
            "This movie review leans very positive:",
            "The tone of this movie review is overwhelmingly positive:",
            "This movie review is heavily skewed towards the positive side:",
            "The overall sentiment of this movie review is predominantly positive:",
            "The positive perspective of this movie review is quite pronounced:",
            "There is a strong inclination towards positive in this movie review:",
            "The author's viewpoint in this movie review is primarily positive:",
            "This movie review tends to be highly optimistic and favorable:",
            "The prevailing sentiment in this movie review is largely positive:",
            "The author's opinion in this movie review is heavily weighted towards positive:",
            "The positive stance of this review is quite prominent:"
        ]
    ],
    "sentiment5-amazon":[
        [
            "This Amazon review leans very negative:",
            "The tone of this Amazon review is overwhelmingly negative:",
            "This Amazon review is heavily skewed towards the negative side:",
            "The overall sentiment of this Amazon review is predominantly negative:",
            "The negative perspective of this Amazon review is quite pronounced:",
            "There is a strong inclination towards negativity in this Amazon review:",
            "The author's viewpoint in this Amazon review is primarily negative:",
            "This Amazon review tends to be highly critical and pessimistic:",
            "The prevailing sentiment in this Amazon review is largely negative:",
            "The author's opinion in this Amazon review is heavily weighted towards negativity:",
            "The negative stance of this review is quite prominent:"
        ],
        [
            "This Amazon review leans somewhat negative:",
            "The tone of this Amazon review is moderately negative:",
            "This Amazon review has a slight inclination towards the negative side:",
            "The overall sentiment of this Amazon review is somewhat negative:",
            "The negative perspective of this Amazon review is somewhat apparent:",
            "There is a mild inclination towards negativity in this Amazon review:",
            "The author's viewpoint in this Amazon review is somewhat negative:",
            "This Amazon review tends to be moderately critical and pessimistic:",
            "The prevailing sentiment in this Amazon review is somewhat negative:",
            "The author's opinion in this Amazon review leans slightly towards negativity:",
            "The negative stance of this review is somewhat evident:"
        ],
        [
            "This Amazon review leans neutral:",
            "The tone of this Amazon review is impartial:",
            "This Amazon review remains balanced and neutral:",
            "The overall sentiment of this Amazon review is neither positive nor negative:",
            "The author takes a neutral stance in this Amazon review:",
            "This Amazon review presents a neutral perspective:",
            "The author's viewpoint in this Amazon review is unbiased and neutral:",
            "This Amazon review maintains a neutral tone throughout:",
            "The prevailing sentiment in this Amazon review is one of neutrality:",
            "The author's opinion in this Amazon review leans towards being neutral:",
            "The review reflects a neutral standpoint:"
        ],
        [
            "This Amazon review leans somewhat positive:",
            "The tone of this Amazon review is moderately positive:",
            "This Amazon review has a slight inclination towards the positive side:",
            "The overall sentiment of this Amazon review is somewhat positive:",
            "The positive perspective of this Amazon review is somewhat apparent:",
            "There is a mild inclination towards positivity in this Amazon review:",
            "The author's viewpoint in this Amazon review is somewhat positive:",
            "This Amazon review tends to be moderately optimistic and favorable:",
            "The prevailing sentiment in this Amazon review is somewhat positive:",
            "The author's opinion in this Amazon review leans slightly towards positivity:",
            "The positive stance of this review is somewhat evident:"
        ],
        [
            "This Amazon review leans very positive:",
            "The tone of this Amazon review is overwhelmingly positive:",
            "This Amazon review is heavily skewed towards the positive side:",
            "The overall sentiment of this Amazon review is predominantly positive:",
            "The positive perspective of this Amazon review is quite pronounced:",
            "There is a strong inclination towards positive in this Amazon review:",
            "The author's viewpoint in this Amazon review is primarily positive:",
            "This Amazon review tends to be highly optimistic and favorable:",
            "The prevailing sentiment in this Amazon review is largely positive:",
            "The author's opinion in this Amazon review is heavily weighted towards positive:",
            "The positive stance of this review is quite prominent:"
        ]
    ],
    "sentiment5-yelp":[
        [
            "This Yelp review leans very negative:",
            "The tone of this Yelp review is overwhelmingly negative:",
            "This Yelp review is heavily skewed towards the negative side:",
            "The overall sentiment of this Yelp review is predominantly negative:",
            "The negative perspective of this Yelp review is quite pronounced:",
            "There is a strong inclination towards negativity in this Yelp review:",
            "The author's viewpoint in this Yelp review is primarily negative:",
            "This Yelp review tends to be highly critical and pessimistic:",
            "The prevailing sentiment in this Yelp review is largely negative:",
            "The author's opinion in this Yelp review is heavily weighted towards negativity:",
            "The negative stance of this review is quite prominent:"
        ],
        [
            "This Yelp review leans somewhat negative:",
            "The tone of this Yelp review is moderately negative:",
            "This Yelp review has a slight inclination towards the negative side:",
            "The overall sentiment of this Yelp review is somewhat negative:",
            "The negative perspective of this Yelp review is somewhat apparent:",
            "There is a mild inclination towards negativity in this Yelp review:",
            "The author's viewpoint in this Yelp review is somewhat negative:",
            "This Yelp review tends to be moderately critical and pessimistic:",
            "The prevailing sentiment in this Yelp review is somewhat negative:",
            "The author's opinion in this Yelp review leans slightly towards negativity:",
            "The negative stance of this review is somewhat evident:"
        ],
        [
            "This Yelp review leans neutral:",
            "The tone of this Yelp review is impartial:",
            "This Yelp review remains balanced and neutral:",
            "The overall sentiment of this Yelp review is neither positive nor negative:",
            "The author takes a neutral stance in this Yelp review:",
            "This Yelp review presents a neutral perspective:",
            "The author's viewpoint in this Yelp review is unbiased and neutral:",
            "This Yelp review maintains a neutral tone throughout:",
            "The prevailing sentiment in this Yelp review is one of neutrality:",
            "The author's opinion in this Yelp review leans towards being neutral:",
            "The review reflects a neutral standpoint:"
        ],
        [
            "This Yelp review leans somewhat positive:",
            "The tone of this Yelp review is moderately positive:",
            "This Yelp review has a slight inclination towards the positive side:",
            "The overall sentiment of this Yelp review is somewhat positive:",
            "The positive perspective of this Yelp review is somewhat apparent:",
            "There is a mild inclination towards positivity in this Yelp review:",
            "The author's viewpoint in this Yelp review is somewhat positive:",
            "This Yelp review tends to be moderately optimistic and favorable:",
            "The prevailing sentiment in this Yelp review is somewhat positive:",
            "The author's opinion in this Yelp review leans slightly towards positivity:",
            "The positive stance of this review is somewhat evident:"
        ],
        [
            "This Yelp review leans very positive:",
            "The tone of this Yelp review is overwhelmingly positive:",
            "This Yelp review is heavily skewed towards the positive side:",
            "The overall sentiment of this Yelp review is predominantly positive:",
            "The positive perspective of this Yelp review is quite pronounced:",
            "There is a strong inclination towards positive in this Yelp review:",
            "The author's viewpoint in this Yelp review is primarily positive:",
            "This Yelp review tends to be highly optimistic and favorable:",
            "The prevailing sentiment in this Yelp review is largely positive:",
            "The author's opinion in this Yelp review is heavily weighted towards positive:",
            "The positive stance of this review is quite prominent:"
        ]
    ],
    "emotion6": [
        [   
            "This tweet emotes sadness:",
            "This tweet reflects a sense of melancholy:",
            "The emotion conveyed in this tweet is sadness:",
            "This tweet evokes a feeling of sorrow:",
            "A sense of sadness permeates this tweet:",
            "The tone of this tweet is filled with sadness:",
            "This tweet expresses a deep sense of sadness:",
            "The sentiment conveyed in this tweet is one of sadness:",
            "This tweet captures the feeling of melancholy:",
            "Sadness resonates through the words of this tweet:",
            "The emotion conveyed by this tweet is one of sadness:"
        ],
        [
            "This tweet emotes joy:",
            "This tweet exudes a sense of joy and happiness:",
            "The emotion conveyed in this tweet is happiness:",
            "This tweet radiates a feeling of delight and happiness:",
            "A sense of happiness permeates this tweet:",
            "The tone of this tweet is filled with joy and happiness:",
            "This tweet expresses a deep sense of happiness:",
            "The sentiment conveyed in this tweet is one of pure happiness:",
            "This tweet captures the feeling of bliss and happiness:",
            "Happiness resonates through the words of this tweet:",
            "The emotion conveyed by this tweet is one of happiness:"
        ],
        [
            "This tweet emotes love:",
            "This tweet exudes a sense of love and affection:",
            "The emotion conveyed in this tweet is love:",
            "This tweet radiates a feeling of warmth and love:",
            "A sense of love permeates this tweet:",
            "The tone of this tweet is filled with love and tenderness:",
            "This tweet expresses a deep sense of love:",
            "The sentiment conveyed in this tweet is one of pure love:",
            "This tweet captures the feeling of passion and love:",
            "Love resonates through the words of this tweet:",
            "The emotion conveyed by this tweet is one of love:"
        ],
        [
            "This tweet emotes anger:",
            "This tweet conveys a strong sense of anger:",
            "The emotion expressed in this tweet is anger:",
            "This tweet emanates a feeling of fury and anger:",
            "A sense of anger permeates this tweet:",
            "The tone of this tweet is filled with anger and frustration:",
            "This tweet reflects a deep sense of anger:",
            "The sentiment conveyed in this tweet is one of intense anger:",
            "This tweet captures the feeling of outrage and anger:",
            "Anger resonates through the words of this tweet:",
            "The emotion conveyed by this tweet is one of anger:"
        ],
        [
            "This tweet emotes fear:",
            "This tweet evokes a sense of fear and apprehension:",
            "The emotion expressed in this tweet is fear:",
            "This tweet instills a feeling of terror and fear:",
            "A sense of fear permeates this tweet:",
            "The tone of this tweet is filled with fear and anxiety:",
            "This tweet reflects a deep sense of fear:",
            "The sentiment conveyed in this tweet is one of fear and dread:",
            "This tweet captures the feeling of unease and fear:",
            "Fear resonates through the words of this tweet:",
            "The emotion conveyed by this tweet is one of fear:"
        ],
        [
            "This tweet emotes surprise:",
            "This tweet elicits a sense of surprise and astonishment:",
            "The emotion expressed in this tweet is surprise:",
            "This tweet brings about a feeling of shock and surprise:",
            "A sense of surprise permeates this tweet:",
            "The tone of this tweet is filled with surprise and amazement:",
            "This tweet evokes a deep sense of surprise:",
            "The sentiment conveyed in this tweet is one of unexpected surprise:",
            "This tweet captures the feeling of astonishment and surprise:",
            "Surprise resonates through the words of this tweet:",
            "The emotion conveyed by this tweet is one of surprise:"
        ],
    ],
    "agnews": [
        [
            "This news is about world affairs:",
            "The topic of this news revolves around global affairs:",
            "The subject matter of this news pertains to worldwide matters:",
            "The focus of this news  is on matters concerning the entire world:",
            "This news passage concerns events and issues on a global scale:",
            "The content of this news extract encompasses the world and its affairs:",
            "The discussion of this news centers around matters of the world:",
            "This news involves the global context and its implications:",
            "The topic of this news explores the broader world perspective:",
            "This news delves into matters that impact the entire world:",
            "The subject matter of this news relates to the world at large:"
        ],
        [
            "This news is about sports:",
            "The focus of this news is on sports-related content:",
            "The topic of this news revolves around the world of sports:",
            "This news passage concerns matters within the realm of sports:",
            "The subject matter of this news pertains to athletic endeavors:",
            "This news explores various aspects of the sporting world:",
            "The discussion of this news centers around sports-related subjects:",
            "This news delves into the realm of competitive athletics:",
            "The content of this news encompasses the world of sports:",
            "The topic of this news involves sports-related events and activities:",
            "This news relates to the exciting world of sports:"
        ],
        [
            "This news is about business:",
            "The topic of this news revolves around matters of business:",
            "The focus of this news is on business-related content:",
            "This news passage concerns various aspects of the business world:",
            "The subject matter of this news pertains to the realm of commerce:",
            "This news explores topics within the scope of business:",
            "The discussion of this news centers around matters of entrepreneurship and commerce:",
            "This news delves into the world of corporate affairs:",
            "The content of this news encompasses business-related subjects:",
            "The topic of this news involves aspects of the commercial landscape:",
            "This news relates to the dynamic world of business and finance:"
        ],
        [
            "This news is about technology:",
            "The topic of this news revolves around matters of technology:",
            "The focus of this news is on technology-related content:",
            "This news passage concerns various aspects of the technological landscape:",
            "The subject matter of this news pertains to the realm of innovation and tech:",
            "This news explores topics within the scope of technology:",
            "The discussion of this news centers around matters of advanced technology:",
            "This news delves into the world of technological advancements:",
            "The content of this news encompasses technology-related subjects:",
            "The topic of this news involves aspects of the digital and technological world:",
            "This news relates to the dynamic field of technology and innovation:"
        ]
    ],
    "dbpedia": [
        [
            "This Wikipedia text is about a company:",
            "This Wikipedia article pertains to a corporation:",
            "The content of this Wikipedia entry discusses a business entity:",
            "This article focuses on a company within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a commercial organization:",
            "This page concerns a corporate entity:",
            "The content of this article revolves around a company:",
            "This Wikipedia text deals with a business:",
            "The topic of discussion in this Wikipedia entry is a company:",
            "The subject of this Wikipedia article is a corporation:",
            "This Wikipedia page provides information about a company:"
        ],
        [
            "This Wikipedia article is about an educational institution:",
            "This Wikipedia entry pertains to an educational institution:",
            "The content of this Wikipedia entry discusses an educational institution:",
            "This article focuses on an educational institution within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is an educational institution:",
            "This page concerns an educational institution:",
            "The content of this article revolves around an educational institution:",
            "This Wikipedia text deals with an educational institution:",
            "The topic of discussion in this Wikipedia entry is an educational institution:",
            "The subject of this Wikipedia article is an educational institution:",
            "This Wikipedia page provides information about an educational institution:"
        ],
        [   
            "This Wikipedia article is about an artist:",
            "This Wikipedia entry pertains to an artist:",
            "The content of this Wikipedia entry discusses an artist:",
            "This article focuses on an artist within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is an artist:",
            "This page concerns an artist:",
            "The content of this article revolves around an artist:",
            "This Wikipedia text deals with an artist:",
            "The topic of discussion in this Wikipedia entry is an artist:",
            "The subject of this Wikipedia article is an artist:",
            "This Wikipedia page provides information about an artist:"
        ],
        [
            "This Wikipedia article is about an athlete:",
            "This Wikipedia entry pertains to an athlete:",
            "The content of this Wikipedia entry discusses an athlete:",
            "This article focuses on an athlete within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is an athlete:",
            "This page concerns an athlete:",
            "The content of this article revolves around an athlete:",
            "This Wikipedia text deals with an athlete:",
            "The topic of discussion in this Wikipedia entry is an athlete:",
            "The subject of this Wikipedia article is an athlete:",
            "This Wikipedia page provides information about an athlete:"
        ],
        [
            "This Wikipedia article is about an office holder:",
            "This Wikipedia entry pertains to an office holder:",
            "The content of this Wikipedia entry discusses an office holder:",
            "This article focuses on an office holder within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is an office holder:",
            "This page concerns an office holder:",
            "The content of this article revolves around an office holder:",
            "This Wikipedia text deals with an office holder:",
            "The topic of discussion in this Wikipedia entry is an office holder:",
            "The subject of this Wikipedia article is an office holder:",
            "This Wikipedia page provides information about an office holder:"
        ],
        [
            "This Wikipedia article is about a means of transportation:",
            "This Wikipedia entry pertains to a means of transportation:",
            "The content of this Wikipedia entry discusses a means of transportation:",
            "This article focuses on a means of transportation within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a means of transportation:",
            "This page concerns a means of transportation:",
            "The content of this article revolves around a means of transportation:",
            "This Wikipedia text deals with a means of transportation:",
            "The topic of discussion in this Wikipedia entry is a means of transportation:",
            "The subject of this Wikipedia article is a means of transportation:",
            "This Wikipedia page provides information about a means of transportation:"
        ],
        [
            "This Wikipedia text is about a building:",
            "This Wikipedia article pertains to a structure:",
            "The content of this Wikipedia entry discusses an building:",
            "This article focuses on a construction within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a constructed building:",
            "This page concerns a physical structure:",
            "The content of this article revolves around a built environment:",
            "This Wikipedia text deals with a man-made construction:",
            "The topic of discussion in this Wikipedia entry is a building:",
            "The subject of this Wikipedia article is a constructed building:",
            "This Wikipedia page provides information about a built structure:"
        ],
        [
            "This Wikipedia text is about a natural place:",
            "This Wikipedia article pertains to a geographic location:",
            "The content of this Wikipedia entry discusses a natural area:",
            "This article focuses on a place in nature within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a natural geographic spot:",
            "This page concerns a location in the natural world:",
            "The content of this article revolves around a natural environment:",
            "This Wikipedia text deals with a place in the natural world:",
            "The topic of discussion in this Wikipedia entry is a natural place:",
            "The subject of this Wikipedia article is a geographic location in nature:",
            "This Wikipedia page provides information about a natural site:"
        ],
        [
            "This Wikipedia text is about a village:",
            "This Wikipedia article pertains to a small settlement:",
            "The content of this Wikipedia entry discusses a rural village:",
            "This article focuses on a village within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a small rural community:",
            "This page concerns a village or hamlet:",
            "The content of this article revolves around a small town or village:",
            "This Wikipedia text deals with a rural village or settlement:",
            "The topic of discussion in this Wikipedia entry is a small community:",
            "The subject of this Wikipedia article is a village:",
            "This Wikipedia page provides information about a rural village:"
        ],
        [
            "This Wikipedia text is about an animal:",
            "This Wikipedia article pertains to a living creature:",
            "The content of this Wikipedia entry discusses a member of the animal kingdom:",
            "This article focuses on an animal within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a specific creature:",
            "This page concerns an animal species:",
            "The content of this article revolves around an organism from the animal kingdom:",
            "This Wikipedia text deals with a particular living being:",
            "The topic of discussion in this Wikipedia entry is an animal species:",
            "The subject of this Wikipedia article is a creature from the animal world:",
            "This Wikipedia page provides information about an animal:"
        ],
        [
            "This Wikipedia text is about a plant:",
            "This Wikipedia article pertains to a living plant:",
            "The content of this Wikipedia entry discusses a member of the plant kingdom:",
            "This article focuses on a plant within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a specific plant species:",
            "This page concerns a type of plant:",
            "The content of this article revolves around a living plant organism:",
            "This Wikipedia text deals with a particular plant:",
            "The topic of discussion in this Wikipedia entry is a plant species:",
            "The subject of this Wikipedia article is a plant from the plant kingdom:",
            "This Wikipedia page provides information about a plant:"
        ],
        [
            "This Wikipedia text is about an album:",
            "This Wikipedia article pertains to a musical record:",
            "The content of this Wikipedia entry discusses a recorded music album:",
            "This article focuses on an album within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a specific music release:",
            "This page concerns a musical recording:",
            "The content of this article revolves around a recorded music collection:",
            "This Wikipedia text deals with a particular album:",
            "The topic of discussion in this Wikipedia entry is a music album:",
            "The subject of this Wikipedia article is a recorded musical work:",
            "This Wikipedia page provides information about a music album:"
        ],
        [
            "This Wikipedia text is about a film:",
            "This Wikipedia article pertains to a cinematic production:",
            "The content of this Wikipedia entry discusses a movie or film:",
            "This article focuses on a film within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a specific motion picture:",
            "This page concerns a cinematic work:",
            "The content of this article revolves around a movie or film production:",
            "This Wikipedia text deals with a particular cinematic creation:",
            "The topic of discussion in this Wikipedia entry is a film:",
            "The subject of this Wikipedia article is a motion picture:",
            "This Wikipedia page provides information about a film:"
        ],
        [
            "This Wikipedia text is about a written work:",
            "This Wikipedia article pertains to a literary composition:",
            "The content of this Wikipedia entry discusses a piece of written literature:",
            "This article focuses on a written work within the context of Wikipedia:",
            "The subject matter of this Wikipedia text is a specific written piece:",
            "This page concerns a literary creation:",
            "The content of this article revolves around a written literary work:",
            "This Wikipedia text deals with a particular written composition:",
            "The topic of discussion in this Wikipedia entry is a written work:",
            "The subject of this Wikipedia article is a piece of written literature:",
            "This Wikipedia page provides information about a written composition:"
        ]
    ],
    "hate_speech18": [ 
        [
            "This Stormfront post contains benign language:",
            "The language used in this Stormfront post is harmless:",
            "The content of this Stormfront message is respectful:",
            "This Stormfront forum post uses inoffensive language:",
            "The wording in this Stormfront post is benign:",
            "The language in this Stormfront message poses no harm:",
            "This Stormfront post employs non-threatening language:",
            "The text within this Stormfront post is free from controversy:",
            "The language used in this Stormfront discussion is innocuous:",
            "This Stormfront post consists of safe and non-controversial language:",
            "The content of this Stormfront message is free from offense:"
            # "The language used in this Stormfront post is harmless:",
            # "The wording in this Stormfront post is inoffensive:",
            # "This Stormfront post employs language that poses no harm or offense:",
            # "The language used in this Stormfront post is benign:",
            # "The tone of this Stormfront post is innocuous and non-threatening:",
            # "The language in this Stormfront post is gentle and non-offensive:",
            # "This Stormfront post avoids using language that may cause harm or offense:",
            # "The wording in this Stormfront post is free from any malicious intent:",
            # "The language used in this Stormfront post is mild and inoffensive:",
            # "This Stormfront post utilizes language that is neutral and non-confrontational:"
        ],
        [
            "This Stormfront post contains hateful language:",
            "The language used in this Stormfront post is offensive:",
            "The content of this Stormfront message is disrespectful:",
            "This Stormfront forum post uses objectionable language:",
            "The wording in this Stormfront post is inappropriate:",
            "The language in this Stormfront message is harmful:",
            "This Stormfront post employs offensive language:",
            "The text within this Stormfront post is offensive and controversial:",
            "The language used in this Stormfront discussion is objectionable:",
            "This Stormfront post consists of offensive and inappropriate language:",
            "The content of this Stormfront message is disrespectful and harmful:"
            # "The language used in this Stormfront post is offensive:",
            # "The wording in this Stormfront post is harmful:",
            # "This Stormfront post employs language that may cause harm or offense:",
            # "The language used in this Stormfront post is derogatory:",
            # "The tone of this Stormfront post is inflammatory and offensive:",
            # "The language in this Stormfront post is aggressive and disrespectful:",
            # "This Stormfront post includes language that may cause harm or offense:",
            # "The wording in this Stormfront post is filled with malicious intent:",
            # "The language used in this Stormfront post is harsh and offensive:",
            # "This Stormfront post utilizes language that is provocative and confrontational:"
        ],
    ],
    'ethos-national_origin':[
        [
            "This social-media post contains hate-speech about something:",
            "This social-media post includes hate-speech targeting a specific subject:",
            "This social-media post features derogatory remarks about something:",
            "This social-media post incorporates offensive language directed at a particular topic:",
            "This social-media post contains hateful remarks about something:",
            "This social-media post includes offensive content pertaining to a specific subject:",
            "This social-media post features derogatory language about something:",
            "This social-media post incorporates instances of offensive language targeting a particular topic:",
            "This social-media post contains hateful language about something:",
            "This social-media post includes instances of hate-speech pertaining to a specific subject:",
            "This social-media post features offensive remarks about something:"
        ],
        [
            "This social-media post contains hate-speech about national origin:",
            "This social-media post includes hate-speech targeting a specific national origin:",
            "This social-media post features derogatory remarks based on national origin:",
            "This social-media post incorporates offensive language directed at a particular national origin:",
            "This social-media post contains nationality related hate-speech:",
            "This social-media post includes nationality related insensitive remarks:",
            "This social-media post features derogatory language targeting a specific national origin:",
            "This social-media post incorporates discriminatory language based on national origin:",
            "This social-media post contains nationality related epithets:",
            "This social-media post includes nationality related offensive content:",
            "This social-media post features derogatory language about national origin:"
        ],
    ],
    'ethos-sexual_orientation':[
        [
            "This social-media post contains hate-speech about something:",
            "This social-media post includes hate-speech targeting a specific subject:",
            "This social-media post features derogatory remarks about something:",
            "This social-media post incorporates offensive language directed at a particular topic:",
            "This social-media post contains hateful remarks about something:",
            "This social-media post includes offensive content pertaining to a specific subject:",
            "This social-media post features derogatory language about something:",
            "This social-media post incorporates instances of offensive language targeting a particular topic:",
            "This social-media post contains hateful language about something:",
            "This social-media post includes instances of hate-speech pertaining to a specific subject:",
            "This social-media post features offensive remarks about something:"
        ],
        [
            "This social-media post contains hate-speech about sexual orientation:",
            "This social-media post includes hate-speech targeting a specific sexual orientation:",
            "This social-media post features derogatory remarks based on sexual orientation:",
            "This social-media post incorporates offensive language directed at a particular sexual orientation:",
            "This social-media post contains sexual orientation-related hate-speech:",
            "This social-media post includes sexual orientation-related insensitive remarks:",
            "This social-media post features derogatory language targeting a specific sexual orientation:",
            "This social-media post incorporates discriminatory language based on sexual orientation:",
            "This social-media post contains sexual orientation-related epithets:",
            "This social-media post includes sexual orientation-related offensive content:",
            "This social-media post features derogatory language about sexual orientation:"
        ],
    ],
    'ethos-race':[
        [
            "This social-media post contains hate-speech about something:",
            "This social-media post includes hate-speech targeting a specific subject:",
            "This social-media post features derogatory remarks about something:",
            "This social-media post incorporates offensive language directed at a particular topic:",
            "This social-media post contains hateful remarks about something:",
            "This social-media post includes offensive content pertaining to a specific subject:",
            "This social-media post features derogatory language about something:",
            "This social-media post incorporates instances of offensive language targeting a particular topic:",
            "This social-media post contains hateful language about something:",
            "This social-media post includes instances of hate-speech pertaining to a specific subject:",
            "This social-media post features offensive remarks about something:"
        ],
        [
            "This social-media post contains hate-speech about race:",
            "This social-media post includes hate-speech targeting a specific race:",
            "This social-media post features derogatory remarks based on race:",
            "This social-media post incorporates offensive language directed at a particular race:",
            "This social-media post contains racial hate-speech:",
            "This social-media post includes racially insensitive remarks:",
            "This social-media post features derogatory language targeting a specific race:",
            "This social-media post incorporates discriminatory language based on race:",
            "This social-media post contains racial epithets:",
            "This social-media post includes racially offensive content:",
            "This social-media post features derogatory language about race:"
        ],
    ],
    'ethos-religion':[
        [
            "This social-media post contains hate-speech about something:",
            "This social-media post includes hate-speech targeting a specific subject:",
            "This social-media post features derogatory remarks about something:",
            "This social-media post incorporates offensive language directed at a particular topic:",
            "This social-media post contains hateful remarks about something:",
            "This social-media post includes offensive content pertaining to a specific subject:",
            "This social-media post features derogatory language about something:",
            "This social-media post incorporates instances of offensive language targeting a particular topic:",
            "This social-media post contains hateful language about something:",
            "This social-media post includes instances of hate-speech pertaining to a specific subject:",
            "This social-media post features offensive remarks about something:"
        ],
        [
            "This social-media post contains hate-speech about religion:",
            "This social-media post includes hate-speech targeting a specific religion:",
            "This social-media post features derogatory remarks based on religion:",
            "This social-media post incorporates offensive language directed at a particular religion:",
            "This social-media post contains religuous hate-speech:",
            "This social-media post includes religuously insensitive remarks:",
            "This social-media post features derogatory language targeting a specific religion:",
            "This social-media post incorporates discriminatory language based on religion:",
            "This social-media post contains religuous epithets:",
            "This social-media post includes religuously offensive content:",
            "This social-media post features derogatory language about religion:"
        ],
    ],
    "rte": [
        ["The premise entails the hypothesis:"],
        ["The premise does not entail the hypothesis:"]
    ],
    "cb": [
        ["The premise entails the hypothesis:"],
        ["The premise does not entail the hypothesis:"]
    ]
}

TASK2ARGS ={
    "sst2": {},
    "adv_sst2": {},
    "advmix_sst2": {},
    "sst5": {},
    "yelp2": {},
    "yelp5": {},
    "poem_sentiment": {},
    "yahoo_answers_topics": {},
    "emotion6": {},
    "agnews": {},
    "trec": {},
    "subjectivity": {},
    "boolq": {},
    "jigsaw": {},
    "hate_speech18": {},
}

# ["It is about World. "],
# ["It is about Sports. "],
# ["It is about Business. "],
# ["It is about Technology. "]