TASK2SIMPLE = {
    "sentiment2": ["{text}"],
    "sentiment2-adv": ["{text}"],
    "sentiment2-advmix": ["{text}"],
    "sentiment2-mr": ["{text}"],
    "sentiment2-cr": ["{text}"],
    "sentiment2-amazon": ["{text}"],
    "poemsentiment2": ["{text}"],
    "finance_sentiment3": ["{text}"],
    "tweet_eval-sentiment": ["{text}"],
    "tweet_eval-hate": ["{text}"],
    "sentiment5": ["{text}"],
    "sentiment5-amazon": ["{text}"],
    "sentiment2-yelp": ["{text}"],
    "sentiment5-yelp": ["{text}"],
    "emotion6": ["{text}"],
    "agnews": ["{text}"],
    "dbpedia": ["{text}"],
    "hate_speech18": ["{text}"],
    "ethos-national_origin": ["{text}"],
    "ethos-sexual_orientation": ["{text}"],
    "ethos-race": ["{text}"],
    "ethos-religion": ["{text}"],
    "rte": ["{text1}  {text2}"],
    "cb": ["{text1}  {text2}"],
}

TASK2CONTEXT = {
    "sentiment2": ["Input: {text}"],
    "sentiment2-adv": ["Input: {text}"],
    "sentiment2-advmix": ["Input: {text}"],
    "sentiment2-mr": ["Input: {text}"],
    "sentiment2-cr": ["Input: {text}"],
    "sentiment2-amazon": ["Input: {text}"],
    "poemsentiment2": ["Input: {text}"],
    "finance_sentiment3": ["Input: {text}"],
    "tweet_eval-sentiment": ["Input: {text}"],
    "tweet_eval-hate": ["Input: {text}"],
    "sentiment5": ["Input: {text}"],
    "sentiment5-amazon": ["Input: {text}"],
    "sentiment2-yelp": ["Input: {text}"],
    "sentiment5-yelp": ["Input: {text}"],
    "emotion6": ["Input: {text}"],
    "agnews": ["Input: {text}"],
    "dbpedia": ["Input: {text}"],
    "hate_speech18": ["Input: {text}"],
    "ethos-national_origin": ["Input: {text}"],
    "ethos-sexual_orientation": ["Input: {text}"],
    "ethos-race": ["Input: {text}"],
    "ethos-religion": ["Input: {text}"],
    "rte": ["{text1}  {text2}"],
    "cb": ["{text1}  {text2}"],
}

TASK2INSTRUCT = {
    "sentiment2": ["Is this text negative or positive? {text}"],
    "sentiment2-adv": ["Is this text negative or positive? {text}"],
    "sentiment2-advmix": ["Is this text negative or positive? {text}"],
    "sentiment2-mr": ["Is this text negative or positive? {text}"],
    "sentiment2-cr": ["Is this text negative or positive? {text}"],
    "sentiment2-amazon": ["Is this text negative or positive? {text}"],
    "poemsentiment2": ["Is the tone of this text negative, positive or neutral? {text}"],
    "finance_sentiment3": ["Is the polarity of this text negative, neutral or positive? {text}"],
    "tweet_eval-sentiment": ["Is this text negative, neutral or positive? {text}"],
    "tweet_eval-hate": ["Does this text contain hate speech? {text}"],
    "sentiment5": ["Is this text very negative, negative, neutral, positive or very positive? {text}"],
    "sentiment5-amazon": ["Is this text very negative, negative, neutral, positive or very positive? {text}"],
    "sentiment2-yelp": ["Is this text negative or positive? {text}"],
    "sentiment5-yelp": ["Is this text very negative, negative, neutral, positive or very positive? {text}"],
    "emotion6": ["Does this text emote sadness, joy, love, anger, fear, or surprise? {text}"],
    "agnews": ["Is the topic of this text world, sports, business, or science and technology? {text}"],
    "dbpedia": ["What is the topic of this text? {text}"],
    "hate_speech18": ["Does this text contain hate speech? {text}"],
    "ethos-national_origin": ["Does this text contain hate speech about national origin? {text}"],
    "ethos-sexual_orientation": ["Does this text contain hate speech about sexual orientation? {text}"],
    "ethos-race": ["Does this text contain hate speech about race? {text}"],
    "ethos-religion": ["Does this text contain hate speech about religion? {text}"],
    "rte": ["{text1}  {text2}"],
    "cb": ["{text1}  {text2}"],
}
    
TASK2LABELSTRINGS = {
    "sentiment2": [
        [   
            " This text exhibits a negative bias.",
            " The inclination of this text is towards the negative side.",
            " There is a unfavorable slant in this text.",
            " The overall tone of this text is negative.",
            " This text shows a leaning against the subject.",
            " There is a negative inclination in this text.",
            " The overall impression of this text is pessimistic.",
            " This text tends to disfavor the subject being discussed.",
            " There is a negative inclination evident in this text.",
            " The general sentiment of this text is negative.",
            " This text leans negative."
        ],
        [
            " This text exhibits a positive bias.",
            " The inclination of this text is towards the positive side.",
            " There is a favorable slant in this text.",
            " The overall tone of this text is positive.",
            " This text shows a leaning in favor of the subject.",
            " There is a positive inclination in this text.",
            " The overall impression of this text is optimistic.",
            " This text tends to favor the subject being discussed.",
            " There is a positive inclination evident in this text.",
            " The general sentiment of this text is positive.",
            " This text leans positive."
        ]
    ],
        "sentiment2-adv": [
        [   
            " This text is meant to trick you but contains a negative bias.",
            " This oddly worded text is actually negative.",
            " A negative bias is on display in this deceptive text.",
            " This text may seem confusing on the surface, but it harbors a negative bias.",
            " In this deceptive text, a negative bias is cleverly concealed.",
            " Behind its confusing facade, this text conceals a negative bias.",
            " This text's misleading nature is overshadowed by its negative bias.",
            " While it may be misleading, this text unmistakably carries a negative bias.",
            " This text, while misleading, clearly showcases a negative bias.",
            " A negative bias lurks beneath the surface of this deceptive text.",
            " While it may not appear so initially, this text reveals a negative bias."
        ],
        [   
            " This text is meant to trick you but contains a positive bias.",
            " This oddly worded text is actually positive.",
            " A positive bias is on display in this deceptive text.",
            " This text may seem confusing on the surface, but it harbors a positive bias.",
            " In this deceptive text, a positive bias is cleverly concealed.",
            " Behind its confusing facade, this text conceals a positive bias.",
            " This text's misleading nature is overshadowed by its positive bias.",
            " While it may be misleading, this text unmistakably carries a positive bias.",
            " This text, while misleading, clearly showcases a positive bias.",
            " A positive bias lurks beneath the surface of this deceptive text.",
            " While it may not appear so initially, this text reveals a positive bias."
        ]
    ],
    # "sentiment2-adv": [
    #     [   
    #         " This misleading text exhibits a negative bias.",
    #         " This seemingly positive text is actually negative.",
    #         " A negative bias is on display in this deceptive text.",
    #         " This text may seem positive on the surface, but it harbors a negative bias.",
    #         " In this deceptive text, a negative bias is cleverly concealed.",
    #         " Behind its facade of positivity, this text conceals a negative bias.",
    #         " This text's misleading nature is overshadowed by its negative bias.",
    #         " While it may be misleading, this text unmistakably carries a negative bias.",
    #         " This text, while misleading, clearly showcases a negative bias.",
    #         " A negative bias lurks beneath the surface of this seemingly positive text.",
    #         " While it may appear positive initially, this text reveals a negative bias."
    #     ],
    #     [   
    #         " This misleading text exhibits a positive bias.",
    #         " This seemingly negative text is actually positive.",
    #         " A positive bias is on display in this deceptive text.",
    #         " This text may seem negative on the surface, but it harbors a positive bias.",
    #         " In this deceptive text, a positive bias is cleverly concealed.",
    #         " Behind its facade of negativity, this text conceals a positive bias.",
    #         " This text's misleading nature is overshadowed by its positive bias.",
    #         " While it may be misleading, this text unmistakably carries a positive bias.",
    #         " This text, while misleading, clearly showcases a positive bias.",
    #         " A positive bias lurks beneath the surface of this seemingly negative text.",
    #         " While it may appear negative initially, this text reveals a positive bias."
    #     ]
    # ],
    "sentiment2-advmix": [
        [   
            " This text exhibits a negative bias.",
            " The inclination of this text is towards the negative side.",
            " There is a unfavorable slant in this text.",
            " The overall tone of this text is negative.",
            " This text shows a leaning against the subject.",
            " There is a negative inclination in this text.",
            " This misleading text exhibits a negative bias.",
            " This seemingly positive text is actually negative.",
            " A negative bias is on display in this deceptive text.",
            " This text may seem positive on the surface, but it harbors a negative bias.",
            " In this deceptive text, a negative bias is cleverly concealed."
        ],
        [
            " This text exhibits a positive bias.",
            " The inclination of this text is towards the positive side.",
            " There is a favorable slant in this text.",
            " The overall tone of this text is positive.",
            " This text shows a leaning in favor of the subject.",
            " There is a positive inclination in this text.",
            " This misleading text exhibits a positive bias.",
            " This seemingly negative text is actually positive.",
            " A positive bias is on display in this deceptive text.",
            " This text may seem negative on the surface, but it harbors a positive bias.",
            " In this deceptive text, a positive bias is cleverly concealed."
        ]
    ],
    "sentiment2-mr": [
        [   
            " This text exhibits a negative bias.",
            " The inclination of this text is towards the negative side.",
            " There is a unfavorable slant in this text.",
            " The overall tone of this text is negative.",
            " This text shows a leaning against the subject.",
            " There is a negative inclination in this text.",
            " The overall impression of this text is pessimistic.",
            " This text tends to disfavor the subject being discussed.",
            " There is a negative inclination evident in this text.",
            " The general sentiment of this text is negative.",
            " This text leans negative."
        ],
        [
            " This text exhibits a positive bias.",
            " The inclination of this text is towards the positive side.",
            " There is a favorable slant in this text.",
            " The overall tone of this text is positive.",
            " This text shows a leaning in favor of the subject.",
            " There is a positive inclination in this text.",
            " The overall impression of this text is optimistic.",
            " This text tends to favor the subject being discussed.",
            " There is a positive inclination evident in this text.",
            " The general sentiment of this text is positive.",
            " This text leans positive."
        ]
    ],
    "sentiment2-cr": [
        [   
            " This text exhibits a negative bias.",
            " The inclination of this text is towards the negative side.",
            " There is a unfavorable slant in this text.",
            " The overall tone of this text is negative.",
            " This text shows a leaning against the subject.",
            " There is a negative inclination in this text.",
            " The overall impression of this text is pessimistic.",
            " This text tends to disfavor the subject being discussed.",
            " There is a negative inclination evident in this text.",
            " The general sentiment of this text is negative.",
            " This text leans negative."
        ],
        [
            " This text exhibits a positive bias.",
            " The inclination of this text is towards the positive side.",
            " There is a favorable slant in this text.",
            " The overall tone of this text is positive.",
            " This text shows a leaning in favor of the subject.",
            " There is a positive inclination in this text.",
            " The overall impression of this text is optimistic.",
            " This text tends to favor the subject being discussed.",
            " There is a positive inclination evident in this text.",
            " The general sentiment of this text is positive.",
            " This text leans positive."
        ]
    ],
    "sentiment2-amazon": [
        [   
            " This text exhibits a negative bias.",
            " The inclination of this text is towards the negative side.",
            " There is a unfavorable slant in this text.",
            " The overall tone of this text is negative.",
            " This text shows a leaning against the subject.",
            " There is a negative inclination in this text.",
            " The overall impression of this text is pessimistic.",
            " This text tends to disfavor the subject being discussed.",
            " There is a negative inclination evident in this text.",
            " The general sentiment of this text is negative.",
            " This text leans negative."
        ],
        [
            " This text exhibits a positive bias.",
            " The inclination of this text is towards the positive side.",
            " There is a favorable slant in this text.",
            " The overall tone of this text is positive.",
            " This text shows a leaning in favor of the subject.",
            " There is a positive inclination in this text.",
            " The overall impression of this text is optimistic.",
            " This text tends to favor the subject being discussed.",
            " There is a positive inclination evident in this text.",
            " The general sentiment of this text is positive.",
            " This text leans positive."
        ]
    ],
    "sentiment2-yelp": [
        [   
            " This text exhibits a negative bias.",
            " The inclination of this text is towards the negative side.",
            " There is a unfavorable slant in this text.",
            " The overall tone of this text is negative.",
            " This text shows a leaning against the subject.",
            " There is a negative inclination in this text.",
            " The overall impression of this text is pessimistic.",
            " This text tends to disfavor the subject being discussed.",
            " There is a negative inclination evident in this text.",
            " The general sentiment of this text is negative.",
            " This text leans negative."
        ],
        [
            " This text exhibits a positive bias.",
            " The inclination of this text is towards the positive side.",
            " There is a favorable slant in this text.",
            " The overall tone of this text is positive.",
            " This text shows a leaning in favor of the subject.",
            " There is a positive inclination in this text.",
            " The overall impression of this text is optimistic.",
            " This text tends to favor the subject being discussed.",
            " There is a positive inclination evident in this text.",
            " The general sentiment of this text is positive.",
            " This text leans positive."
        ]
    ],
    "poemsentiment2": [
        [
            " This text has a negative tone.",
            " The verse of this poem embodies a negative tone.",
            " A pessimistic sentiment lingers in this text.",
            " This text exudes a dark and gloomy atmosphere.",
            " The tone of this text leans towards negativity.",
            " A sense of despair and sadness permeates the lines of this text.",
            " The verse of this poem reflects a somber and disheartening mood.",
            " The negative undertone of this text evokes a melancholic feeling.",
            " The sentiment conveyed by this text is predominantly negative.",
            " The verse of this poem paints a bleak and desolate picture.",
            " A somber aura envelops the words of this text."
        ],
        [
            " This text has a positive tone.",
            " The verse of this poem radiates a positive tone.",
            " A hopeful and uplifting sentiment permeates this text.",
            " This text exudes an optimistic and joyful atmosphere.",
            " The tone of this text leans towards positivity.",
            " A sense of beauty and inspiration fills the lines of this text.",
            " The verse of this poem reflects a celebratory and enthusiastic mood.",
            " The positive undertone of this text evokes a sense of delight.",
            " The sentiment conveyed by this text is predominantly positive.",
            " The verse of this poem paints a vibrant and uplifting picture.",
            " An uplifting aura envelops the words of this text."
        ],
        [
            " This text has a neutral tone.",
            " The verse of this poem maintains a neutral tone.",
            " A balanced and impartial sentiment characterizes this text.",
            " This text conveys a neutral and unbiased atmosphere.",
            " The tone of this text remains neutral throughout.",
            " A sense of neutrality and objectivity pervades the lines of this text.",
            " The verse of this poem reflects a calm and detached mood.",
            " The sentiment conveyed by this text is neither positive nor negative.",
            " The verse of this poem paints a picture devoid of strong emotions.",
            " An atmosphere of neutrality envelops the words of this text.",
            " The tone of this text is consistently neutral."
        ]
    ],
    "finance_sentiment3": [
        [  
            " This text expresses a negative polarity.",
            " This financial news snippet conveys a bearish sentiment.",
            " The tone of this text leans towards the negative.",
            " This financial news segment reflects a pessimistic outlook.",
            " A negative undertone permeates this financial news extract.",
            " The sentiment conveyed by this financial news snippet is predominantly negative.",
            " This financial news passage exudes a downbeat sentiment.",
            " The overall tone of this text is unfavorable.",
            " Negativity prevails in this financial news segment.",
            " This financial news snippet presents a gloomy perspective.",
            " The sentiment expressed in this text is largely negative."
        ], 
        [   
            " This text expresses no polarity.",
            " This financial news snippet lacks any discernible polarity.",
            " The tone of this text is devoid of any explicit positivity or negativity.",
            " This financial news segment presents information without a clear emotional bias.",
            " No distinct polarity is evident in this financial news extract.",
            " The sentiment conveyed by this financial news snippet is neutral and non-committal.",
            " This financial news passage remains neutral in its presentation.",
            " The overall tone of this text is neither positive nor negative.",
            " This financial news snippet provides an objective account without expressing any polarity.",
            " The sentiment expressed in this text is neutral throughout.",
            " This text maintains a neutral standpoint."
        ], 
        [   
            " This text expresses a positive polarity.",
            " This financial news snippet exudes a positive sentiment.",
            " The tone of this text leans towards the positive.",
            " This financial news segment reflects an optimistic outlook.",
            " A positive undertone permeates this financial news extract.",
            " The sentiment conveyed by this financial news snippet is predominantly positive.",
            " This financial news passage radiates positivity.",
            " The overall tone of this text is favorable.",
            " Positivity prevails in this financial news segment.",
            " This financial news snippet presents an encouraging perspective.",
            " The sentiment expressed in this text is largely positive."
        ]
    ],
    "tweet_eval-sentiment": [
        [   
            " This text exhibits a negative bias.",
            " The inclination of this text is towards the negative side.",
            " There is a unfavorable slant in this text.",
            " The overall tone of this text is negative.",
            " This text shows a leaning against the subject.",
            " There is a negative inclination in this text.",
            " The overall impression of this text is pessimistic.",
            " This text tends to disfavor the subject being discussed.",
            " There is a negative inclination evident in this text.",
            " The general sentiment of this text is negative.",
            " This text leans negative."
        ],
        [
            " This text leans neutral.",
            " The tone of this text is impartial.",
            " This text remains balanced and neutral.",
            " The overall sentiment of this text is neither positive nor negative.",
            " The author takes a neutral stance in this text.",
            " This text presents a neutral perspective.",
            " The author's viewpoint in this text is unbiased and neutral.",
            " This text maintains a neutral tone throughout.",
            " The prevailing sentiment in this text is one of neutrality.",
            " The author's opinion in this text leans towards being neutral.",
            " The text reflects a neutral standpoint."
        ],
        [
            " This text exhibits a positive bias.",
            " The inclination of this text is towards the positive side.",
            " There is a favorable slant in this text.",
            " The overall tone of this text is positive.",
            " This text shows a leaning in favor of the subject.",
            " There is a positive inclination in this text.",
            " The overall impression of this text is optimistic.",
            " This text tends to favor the subject being discussed.",
            " There is a positive inclination evident in this text.",
            " The general sentiment of this text is positive.",
            " This text leans positive."
        ],
    ],
     "tweet_eval-hate": [ 
        [
            " This text contains benign language.",
            " The language used in this text is harmless.",
            " The content of this text is respectful.",
            " This text uses inoffensive language.",
            " The wording in this text is benign.",
            " The language in this text poses no harm.",
            " This text employs non-threatening language.",
            " The text within this text is free from controversy.",
            " The language used in this text is innocuous.",
            " This text consists of safe and non-controversial language.",
            " The content of this text is free from offense."
        ],
        [
            " This text contains hateful language.",
            " The language used in this text is offensive.",
            " The content of this text is disrespectful.",
            " This text uses objectionable language.",
            " The wording in this text is inappropriate.",
            " The language in this text is harmful.",
            " This text employs offensive language.",
            " The text within this text is offensive and controversial.",
            " The language used in this text is objectionable.",
            " This text consists of offensive and inappropriate language.",
            " The content of this text is disrespectful and harmful."
        ],
    ],
    "sentiment5":[
        [
            " This text leans very negative.",
            " The tone of this text is overwhelmingly negative.",
            " This text is heavily skewed towards the negative side.",
            " The overall sentiment of this text is predominantly negative.",
            " The negative perspective of this text is quite pronounced.",
            " There is a strong inclination towards negativity in this text.",
            " The author's viewpoint in this text is primarily negative.",
            " This text tends to be highly critical and pessimistic.",
            " The prevailing sentiment in this text is largely negative.",
            " The author's opinion in this text is heavily weighted towards negativity.",
            " The negative stance of this review is quite prominent."
        ],
        [
            " This text leans somewhat negative.",
            " The tone of this text is moderately negative.",
            " This text has a slight inclination towards the negative side.",
            " The overall sentiment of this text is somewhat negative.",
            " The negative perspective of this text is somewhat apparent.",
            " There is a mild inclination towards negativity in this text.",
            " The author's viewpoint in this text is somewhat negative.",
            " This text tends to be moderately critical and pessimistic.",
            " The prevailing sentiment in this text is somewhat negative.",
            " The author's opinion in this text leans slightly towards negativity.",
            " The negative stance of this review is somewhat evident."
        ],
        [
            " This text leans neutral.",
            " The tone of this text is impartial.",
            " This text remains balanced and neutral.",
            " The overall sentiment of this text is neither positive nor negative.",
            " The author takes a neutral stance in this text.",
            " This text presents a neutral perspective.",
            " The author's viewpoint in this text is unbiased and neutral.",
            " This text maintains a neutral tone throughout.",
            " The prevailing sentiment in this text is one of neutrality.",
            " The author's opinion in this text leans towards being neutral.",
            " The review reflects a neutral standpoint."
        ],
        [
            " This text leans somewhat positive.",
            " The tone of this text is moderately positive.",
            " This text has a slight inclination towards the positive side.",
            " The overall sentiment of this text is somewhat positive.",
            " The positive perspective of this text is somewhat apparent.",
            " There is a mild inclination towards positivity in this text.",
            " The author's viewpoint in this text is somewhat positive.",
            " This text tends to be moderately optimistic and favorable.",
            " The prevailing sentiment in this text is somewhat positive.",
            " The author's opinion in this text leans slightly towards positivity.",
            " The positive stance of this review is somewhat evident."
        ],
        [
            " This text leans very positive.",
            " The tone of this text is overwhelmingly positive.",
            " This text is heavily skewed towards the positive side.",
            " The overall sentiment of this text is predominantly positive.",
            " The positive perspective of this text is quite pronounced.",
            " There is a strong inclination towards positive in this text.",
            " The author's viewpoint in this text is primarily positive.",
            " This text tends to be highly optimistic and favorable.",
            " The prevailing sentiment in this text is largely positive.",
            " The author's opinion in this text is heavily weighted towards positive.",
            " The positive stance of this review is quite prominent."
        ]
    ],
    "sentiment5-amazon":[
        [
            " This text leans very negative.",
            " The tone of this text is overwhelmingly negative.",
            " This text is heavily skewed towards the negative side.",
            " The overall sentiment of this text is predominantly negative.",
            " The negative perspective of this text is quite pronounced.",
            " There is a strong inclination towards negativity in this text.",
            " The author's viewpoint in this text is primarily negative.",
            " This text tends to be highly critical and pessimistic.",
            " The prevailing sentiment in this text is largely negative.",
            " The author's opinion in this text is heavily weighted towards negativity.",
            " The negative stance of this review is quite prominent."
        ],
        [
            " This text leans somewhat negative.",
            " The tone of this text is moderately negative.",
            " This text has a slight inclination towards the negative side.",
            " The overall sentiment of this text is somewhat negative.",
            " The negative perspective of this text is somewhat apparent.",
            " There is a mild inclination towards negativity in this text.",
            " The author's viewpoint in this text is somewhat negative.",
            " This text tends to be moderately critical and pessimistic.",
            " The prevailing sentiment in this text is somewhat negative.",
            " The author's opinion in this text leans slightly towards negativity.",
            " The negative stance of this review is somewhat evident."
        ],
        [
            " This text leans neutral.",
            " The tone of this text is impartial.",
            " This text remains balanced and neutral.",
            " The overall sentiment of this text is neither positive nor negative.",
            " The author takes a neutral stance in this text.",
            " This text presents a neutral perspective.",
            " The author's viewpoint in this text is unbiased and neutral.",
            " This text maintains a neutral tone throughout.",
            " The prevailing sentiment in this text is one of neutrality.",
            " The author's opinion in this text leans towards being neutral.",
            " The review reflects a neutral standpoint."
        ],
        [
            " This text leans somewhat positive.",
            " The tone of this text is moderately positive.",
            " This text has a slight inclination towards the positive side.",
            " The overall sentiment of this text is somewhat positive.",
            " The positive perspective of this text is somewhat apparent.",
            " There is a mild inclination towards positivity in this text.",
            " The author's viewpoint in this text is somewhat positive.",
            " This text tends to be moderately optimistic and favorable.",
            " The prevailing sentiment in this text is somewhat positive.",
            " The author's opinion in this text leans slightly towards positivity.",
            " The positive stance of this review is somewhat evident."
        ],
        [
            " This text leans very positive.",
            " The tone of this text is overwhelmingly positive.",
            " This text is heavily skewed towards the positive side.",
            " The overall sentiment of this text is predominantly positive.",
            " The positive perspective of this text is quite pronounced.",
            " There is a strong inclination towards positive in this text.",
            " The author's viewpoint in this text is primarily positive.",
            " This text tends to be highly optimistic and favorable.",
            " The prevailing sentiment in this text is largely positive.",
            " The author's opinion in this text is heavily weighted towards positive.",
            " The positive stance of this review is quite prominent."
        ]
    ],
    "sentiment5-yelp":[
        [
            " This text leans very negative.",
            " The tone of this text is overwhelmingly negative.",
            " This text is heavily skewed towards the negative side.",
            " The overall sentiment of this text is predominantly negative.",
            " The negative perspective of this text is quite pronounced.",
            " There is a strong inclination towards negativity in this text.",
            " The author's viewpoint in this text is primarily negative.",
            " This text tends to be highly critical and pessimistic.",
            " The prevailing sentiment in this text is largely negative.",
            " The author's opinion in this text is heavily weighted towards negativity.",
            " The negative stance of this review is quite prominent."
        ],
        [
            " This text leans somewhat negative.",
            " The tone of this text is moderately negative.",
            " This text has a slight inclination towards the negative side.",
            " The overall sentiment of this text is somewhat negative.",
            " The negative perspective of this text is somewhat apparent.",
            " There is a mild inclination towards negativity in this text.",
            " The author's viewpoint in this text is somewhat negative.",
            " This text tends to be moderately critical and pessimistic.",
            " The prevailing sentiment in this text is somewhat negative.",
            " The author's opinion in this text leans slightly towards negativity.",
            " The negative stance of this review is somewhat evident."
        ],
        [
            " This text leans neutral.",
            " The tone of this text is impartial.",
            " This text remains balanced and neutral.",
            " The overall sentiment of this text is neither positive nor negative.",
            " The author takes a neutral stance in this text.",
            " This text presents a neutral perspective.",
            " The author's viewpoint in this text is unbiased and neutral.",
            " This text maintains a neutral tone throughout.",
            " The prevailing sentiment in this text is one of neutrality.",
            " The author's opinion in this text leans towards being neutral.",
            " The review reflects a neutral standpoint."
        ],
        [
            " This text leans somewhat positive.",
            " The tone of this text is moderately positive.",
            " This text has a slight inclination towards the positive side.",
            " The overall sentiment of this text is somewhat positive.",
            " The positive perspective of this text is somewhat apparent.",
            " There is a mild inclination towards positivity in this text.",
            " The author's viewpoint in this text is somewhat positive.",
            " This text tends to be moderately optimistic and favorable.",
            " The prevailing sentiment in this text is somewhat positive.",
            " The author's opinion in this text leans slightly towards positivity.",
            " The positive stance of this review is somewhat evident."
        ],
        [
            " This text leans very positive.",
            " The tone of this text is overwhelmingly positive.",
            " This text is heavily skewed towards the positive side.",
            " The overall sentiment of this text is predominantly positive.",
            " The positive perspective of this text is quite pronounced.",
            " There is a strong inclination towards positive in this text.",
            " The author's viewpoint in this text is primarily positive.",
            " This text tends to be highly optimistic and favorable.",
            " The prevailing sentiment in this text is largely positive.",
            " The author's opinion in this text is heavily weighted towards positive.",
            " The positive stance of this review is quite prominent."
        ]
    ],
    "emotion6": [
        [   
            " This text emotes sadness.",
            " This text reflects a sense of melancholy.",
            " The emotion conveyed in this text is sadness.",
            " This text evokes a feeling of sorrow.",
            " A sense of sadness permeates this text.",
            " The tone of this text is filled with sadness.",
            " This text expresses a deep sense of sadness.",
            " The sentiment conveyed in this text is one of sadness.",
            " This text captures the feeling of melancholy.",
            " Sadness resonates through the words of this text.",
            " The emotion conveyed by this text is one of sadness."
        ],
        [
            " This text emotes joy.",
            " This text exudes a sense of joy and happiness.",
            " The emotion conveyed in this text is happiness.",
            " This text radiates a feeling of delight and happiness.",
            " A sense of happiness permeates this text.",
            " The tone of this text is filled with joy and happiness.",
            " This text expresses a deep sense of happiness.",
            " The sentiment conveyed in this text is one of pure happiness.",
            " This text captures the feeling of bliss and happiness.",
            " Happiness resonates through the words of this text.",
            " The emotion conveyed by this text is one of happiness."
        ],
        [
            " This text emotes love.",
            " This text exudes a sense of love and affection.",
            " The emotion conveyed in this text is love.",
            " This text radiates a feeling of warmth and love.",
            " A sense of love permeates this text.",
            " The tone of this text is filled with love and tenderness.",
            " This text expresses a deep sense of love.",
            " The sentiment conveyed in this text is one of pure love.",
            " This text captures the feeling of passion and love.",
            " Love resonates through the words of this text.",
            " The emotion conveyed by this text is one of love."
        ],
        [
            " This text emotes anger.",
            " This text conveys a strong sense of anger.",
            " The emotion expressed in this text is anger.",
            " This text emanates a feeling of fury and anger.",
            " A sense of anger permeates this text.",
            " The tone of this text is filled with anger and frustration.",
            " This text reflects a deep sense of anger.",
            " The sentiment conveyed in this text is one of intense anger.",
            " This text captures the feeling of outrage and anger.",
            " Anger resonates through the words of this text.",
            " The emotion conveyed by this text is one of anger."
        ],
        [
            " This text emotes fear.",
            " This text evokes a sense of fear and apprehension.",
            " The emotion expressed in this text is fear.",
            " This text instills a feeling of terror and fear.",
            " A sense of fear permeates this text.",
            " The tone of this text is filled with fear and anxiety.",
            " This text reflects a deep sense of fear.",
            " The sentiment conveyed in this text is one of fear and dread.",
            " This text captures the feeling of unease and fear.",
            " Fear resonates through the words of this text.",
            " The emotion conveyed by this text is one of fear."
        ],
        [
            " This text emotes surprise.",
            " This text elicits a sense of surprise and astonishment.",
            " The emotion expressed in this text is surprise.",
            " This text brings about a feeling of shock and surprise.",
            " A sense of surprise permeates this text.",
            " The tone of this text is filled with surprise and amazement.",
            " This text evokes a deep sense of surprise.",
            " The sentiment conveyed in this text is one of unexpected surprise.",
            " This text captures the feeling of astonishment and surprise.",
            " Surprise resonates through the words of this text.",
            " The emotion conveyed by this text is one of surprise."
        ],
    ],
    "agnews": [
        [
            " This text is about world affairs.",
            " The topic of this text revolves around global affairs.",
            " The subject matter of this text pertains to worldwide matters.",
            " The focus of this text  is on matters concerning the entire world.",
            " This text concerns events and issues on a global scale.",
            " The content of this text encompasses the world and its affairs.",
            " The discussion of this text centers around matters of the world.",
            " This text involves the global context and its implications.",
            " The topic of this text explores the broader world perspective.",
            " This text delves into matters that impact the entire world.",
            " The subject matter of this text relates to the world at large."
        ],
        [
            " This text is about sports.",
            " The focus of this text is on sports-related content.",
            " The topic of this text revolves around the world of sports.",
            " This text concerns matters within the realm of sports.",
            " The subject matter of this text pertains to athletic endeavors.",
            " This text explores various aspects of the sporting world.",
            " The discussion of this text centers around sports-related subjects.",
            " This text delves into the realm of competitive athletics.",
            " The content of this text encompasses the world of sports.",
            " The topic of this text involves sports-related events and activities.",
            " This text relates to the exciting world of sports."
        ],
        [
            " This text is about business.",
            " The topic of this text revolves around matters of business.",
            " The focus of this text is on business-related content.",
            " This text concerns various aspects of the business world.",
            " The subject matter of this text pertains to the realm of commerce.",
            " This text explores topics within the scope of business.",
            " The discussion of this text centers around matters of entrepreneurship and commerce.",
            " This text delves into the world of corporate affairs.",
            " The content of this text encompasses business-related subjects.",
            " The topic of this text involves aspects of the commercial landscape.",
            " This text relates to the dynamic world of business and finance."
        ],
        [
            " This text is about science and technology.",
            " The topic of this text revolves around matters of technology.",
            " The focus of this text is on technology-related content.",
            " This text concerns various aspects of the technological landscape.",
            " The subject matter of this text pertains to the realm of innovation and tech.",
            " This text explores topics within the scope of technology.",
            " The discussion of this text centers around matters of advanced technology.",
            " This text delves into the world of technological advancements.",
            " The content of this text encompasses technology-related subjects.",
            " The topic of this text involves aspects of the digital and technological world.",
            " This text relates to the dynamic field of technology and innovation."
        ]
    ],
    "dbpedia": [
        [
            " This text is about a company.",
            " This text pertains to a corporation.",
            " The content of this text discusses a business entity.",
            " This text focuses on a company.",
            " The subject matter of this text is a commercial organization.",
            " This page concerns a corporate entity.",
            " The content of this text revolves around a company.",
            " This text deals with a business.",
            " The topic of discussion in this text is a company.",
            " The subject of this text is a corporation.",
            " This text provides information about a company."
        ],
        [
            " This text is about an educational institution.",
            " This text pertains to an educational institution.",
            " The content of this text discusses an educational institution.",
            " This text focuses on an educational institution.",
            " The subject matter of this text is an educational institution.",
            " This page concerns an educational institution.",
            " The content of this text revolves around an educational institution.",
            " This text deals with an educational institution.",
            " The topic of discussion in this text is an educational institution.",
            " The subject of this text is an educational institution.",
            " This text provides information about an educational institution."
        ],
        [   
            " This text is about an artist.",
            " This text pertains to an artist.",
            " The content of this text discusses an artist.",
            " This text focuses on an artist.",
            " The subject matter of this text is an artist.",
            " This page concerns an artist.",
            " The content of this text revolves around an artist.",
            " This text deals with an artist.",
            " The topic of discussion in this text is an artist.",
            " The subject of this text is an artist.",
            " This text provides information about an artist."
        ],
        [
            " This text is about an athlete.",
            " This text pertains to an athlete.",
            " The content of this text discusses an athlete.",
            " This text focuses on an athlete.",
            " The subject matter of this text is an athlete.",
            " This page concerns an athlete.",
            " The content of this text revolves around an athlete.",
            " This text deals with an athlete.",
            " The topic of discussion in this text is an athlete.",
            " The subject of this text is an athlete.",
            " This text provides information about an athlete."
        ],
        [
            " This text is about an office holder.",
            " This text pertains to an office holder.",
            " The content of this text discusses an office holder.",
            " This text focuses on an office holder.",
            " The subject matter of this text is an office holder.",
            " This page concerns an office holder.",
            " The content of this text revolves around an office holder.",
            " This text deals with an office holder.",
            " The topic of discussion in this text is an office holder.",
            " The subject of this text is an office holder.",
            " This text provides information about an office holder."
        ],
        [
            " This text is about a means of transportation.",
            " This text pertains to a means of transportation.",
            " The content of this text discusses a means of transportation.",
            " This text focuses on a means of transportation.",
            " The subject matter of this text is a means of transportation.",
            " This page concerns a means of transportation.",
            " The content of this text revolves around a means of transportation.",
            " This text deals with a means of transportation.",
            " The topic of discussion in this text is a means of transportation.",
            " The subject of this text is a means of transportation.",
            " This text provides information about a means of transportation."
        ],
        [
            " This text is about a building.",
            " This text pertains to a structure.",
            " The content of this text discusses an edifice.",
            " This text focuses on a construction.",
            " The subject matter of this text is a constructed building.",
            " This page concerns a physical structure.",
            " The content of this text revolves around a built environment.",
            " This text deals with a man-made construction.",
            " The topic of discussion in this text is a building.",
            " The subject of this text is a constructed edifice.",
            " This text provides information about a built structure."
        ],
        [
            " This text is about a natural place.",
            " This text pertains to a geographic location.",
            " The content of this text discusses a natural area.",
            " This text focuses on a place in nature.",
            " The subject matter of this text is a natural geographic spot.",
            " This page concerns a location in the natural world.",
            " The content of this text revolves around a natural environment.",
            " This text deals with a place in the natural world.",
            " The topic of discussion in this text is a natural place.",
            " The subject of this text is a geographic location in nature.",
            " This text provides information about a natural site."
        ],
        [
            " This text is about a village.",
            " This text pertains to a small settlement.",
            " The content of this text discusses a rural village.",
            " This text focuses on a village.",
            " The subject matter of this text is a small rural community.",
            " This page concerns a village or hamlet.",
            " The content of this text revolves around a small town or village.",
            " This text deals with a rural village or settlement.",
            " The topic of discussion in this text is a small community.",
            " The subject of this text is a village.",
            " This text provides information about a rural village."
        ],
        [
            " This text is about an animal.",
            " This text pertains to a living creature.",
            " The content of this text discusses a member of the animal kingdom.",
            " This text focuses on an animal.",
            " The subject matter of this text is a specific creature.",
            " This page concerns an animal species.",
            " The content of this text revolves around an organism from the animal kingdom.",
            " This text deals with a particular living being.",
            " The topic of discussion in this text is an animal species.",
            " The subject of this text is a creature from the animal world.",
            " This text provides information about an animal."
        ],
        [
            " This text is about a plant.",
            " This text pertains to a living plant.",
            " The content of this text discusses a member of the plant kingdom.",
            " This text focuses on a plant.",
            " The subject matter of this text is a specific plant species.",
            " This page concerns a type of plant.",
            " The content of this text revolves around a living plant organism.",
            " This text deals with a particular plant.",
            " The topic of discussion in this text is a plant species.",
            " The subject of this text is a plant from the plant kingdom.",
            " This text provides information about a plant."
        ],
        [
            " This text is about an album.",
            " This text pertains to a musical record.",
            " The content of this text discusses a recorded music album.",
            " This text focuses on an album.",
            " The subject matter of this text is a specific music release.",
            " This page concerns a musical recording.",
            " The content of this text revolves around a recorded music collection.",
            " This text deals with a particular album.",
            " The topic of discussion in this text is a music album.",
            " The subject of this text is a recorded musical work.",
            " This text provides information about a music album."
        ],
        [
            " This text is about a film.",
            " This text pertains to a cinematic production.",
            " The content of this text discusses a movie or film.",
            " This text focuses on a film.",
            " The subject matter of this text is a specific motion picture.",
            " This page concerns a cinematic work.",
            " The content of this text revolves around a movie or film production.",
            " This text deals with a particular cinematic creation.",
            " The topic of discussion in this text is a film.",
            " The subject of this text is a motion picture.",
            " This text provides information about a film."
        ],
        [
            " This text is about a written work.",
            " This text pertains to a literary composition.",
            " The content of this text discusses a piece of written literature.",
            " This text focuses on a written work.",
            " The subject matter of this text is a specific written piece.",
            " This page concerns a literary creation.",
            " The content of this text revolves around a written literary work.",
            " This text deals with a particular written composition.",
            " The topic of discussion in this text is a written work.",
            " The subject of this text is a piece of written literature.",
            " This text provides information about a written composition."
        ]
    ],
    "hate_speech18": [ 
        [
            " This text contains benign language.",
            " The language used in this text is harmless.",
            " The content of this Stormfront message is respectful.",
            " This Stormfront forum post uses inoffensive language.",
            " The wording in this text is benign.",
            " The language in this Stormfront message poses no harm.",
            " This text employs non-threatening language.",
            " The text within this text is free from controversy.",
            " The language used in this Stormfront discussion is innocuous.",
            " This text consists of safe and non-controversial language.",
            " The content of this Stormfront message is free from offense"
            #  "The language used in this text is harmless.",
            #  "The wording in this text is inoffensive.",
            #  "This text employs language that poses no harm or offense.",
            #  "The language used in this text is benign.",
            #  "The tone of this text is innocuous and non-threatening.",
            #  "The language in this text is gentle and non-offensive.",
            #  "This text avoids using language that may cause harm or offense.",
            #  "The wording in this text is free from any malicious intent.",
            #  "The language used in this text is mild and inoffensive.",
            #  "This text utilizes language that is neutral and non-confrontational"
        ],
        [
            " This text contains hateful language.",
            " The language used in this text is offensive.",
            " The content of this Stormfront message is disrespectful.",
            " This Stormfront forum post uses objectionable language.",
            " The wording in this text is inappropriate.",
            " The language in this Stormfront message is harmful.",
            " This text employs offensive language.",
            " The text within this text is offensive and controversial.",
            " The language used in this Stormfront discussion is objectionable.",
            " This text consists of offensive and inappropriate language.",
            " The content of this Stormfront message is disrespectful and harmful"
            #  "The language used in this text is offensive.",
            #  "The wording in this text is harmful.",
            #  "This text employs language that may cause harm or offense.",
            #  "The language used in this text is derogatory.",
            #  "The tone of this text is inflammatory and offensive.",
            #  "The language in this text is aggressive and disrespectful.",
            #  "This text includes language that may cause harm or offense.",
            #  "The wording in this text is filled with malicious intent.",
            #  "The language used in this text is harsh and offensive.",
            #  "This text utilizes language that is provocative and confrontational"
        ],
    ],
    'ethos-national_origin':[
        [
            " This text contains hate-speech about something.",
            " This text includes hate-speech targeting a specific subject.",
            " This text features derogatory remarks about something.",
            " This text incorporates offensive language directed at a particular topic.",
            " This text contains hateful remarks about something.",
            " This text includes offensive content pertaining to a specific subject.",
            " This text features derogatory language about something.",
            " This text incorporates instances of offensive language targeting a particular topic.",
            " This text contains hateful language about something.",
            " This text includes instances of hate-speech pertaining to a specific subject.",
            " This text features offensive remarks about something."
        ],
        [
            " This text contains hate-speech about national origin.",
            " This text includes hate-speech targeting a specific national origin.",
            " This text features derogatory remarks based on national origin.",
            " This text incorporates offensive language directed at a particular national origin.",
            " This text contains nationality related hate-speech.",
            " This text includes nationality related insensitive remarks.",
            " This text features derogatory language targeting a specific national origin.",
            " This text incorporates discriminatory language based on national origin.",
            " This text contains nationality related epithets.",
            " This text includes nationality related offensive content.",
            " This text features derogatory language about national origin."
        ],
    ],
    'ethos-sexual_orientation':[
        [
            " This text contains hate-speech about something.",
            " This text includes hate-speech targeting a specific subject.",
            " This text features derogatory remarks about something.",
            " This text incorporates offensive language directed at a particular topic.",
            " This text contains hateful remarks about something.",
            " This text includes offensive content pertaining to a specific subject.",
            " This text features derogatory language about something.",
            " This text incorporates instances of offensive language targeting a particular topic.",
            " This text contains hateful language about something.",
            " This text includes instances of hate-speech pertaining to a specific subject.",
            " This text features offensive remarks about something."
        ],
        [
            " This text contains hate-speech about sexual orientation.",
            " This text includes hate-speech targeting a specific sexual orientation.",
            " This text features derogatory remarks based on sexual orientation.",
            " This text incorporates offensive language directed at a particular sexual orientation.",
            " This text contains sexual orientation-related hate-speech.",
            " This text includes sexual orientation-related insensitive remarks.",
            " This text features derogatory language targeting a specific sexual orientation.",
            " This text incorporates discriminatory language based on sexual orientation.",
            " This text contains sexual orientation-related epithets.",
            " This text includes sexual orientation-related offensive content.",
            " This text features derogatory language about sexual orientation."
        ],
    ],
    'ethos-race':[
        [
            " This text contains hate-speech about something.",
            " This text includes hate-speech targeting a specific subject.",
            " This text features derogatory remarks about something.",
            " This text incorporates offensive language directed at a particular topic.",
            " This text contains hateful remarks about something.",
            " This text includes offensive content pertaining to a specific subject.",
            " This text features derogatory language about something.",
            " This text incorporates instances of offensive language targeting a particular topic.",
            " This text contains hateful language about something.",
            " This text includes instances of hate-speech pertaining to a specific subject.",
            " This text features offensive remarks about something."
        ],
        [
            " This text contains hate-speech about race.",
            " This text includes hate-speech targeting a specific race.",
            " This text features derogatory remarks based on race.",
            " This text incorporates offensive language directed at a particular race.",
            " This text contains racial hate-speech.",
            " This text includes racially insensitive remarks.",
            " This text features derogatory language targeting a specific race.",
            " This text incorporates discriminatory language based on race.",
            " This text contains racial epithets.",
            " This text includes racially offensive content.",
            " This text features derogatory language about race."
        ],
    ],
    'ethos-religion':[
        [
            " This text contains hate-speech about something.",
            " This text includes hate-speech targeting a specific subject.",
            " This text features derogatory remarks about something.",
            " This text incorporates offensive language directed at a particular topic.",
            " This text contains hateful remarks about something.",
            " This text includes offensive content pertaining to a specific subject.",
            " This text features derogatory language about something.",
            " This text incorporates instances of offensive language targeting a particular topic.",
            " This text contains hateful language about something.",
            " This text includes instances of hate-speech pertaining to a specific subject.",
            " This text features offensive remarks about something."
        ],
        [
            " This text contains hate-speech about religion.",
            " This text includes hate-speech targeting a specific religion.",
            " This text features derogatory remarks based on religion.",
            " This text incorporates offensive language directed at a particular religion.",
            " This text contains religuous hate-speech.",
            " This text includes religuously insensitive remarks.",
            " This text features derogatory language targeting a specific religion.",
            " This text incorporates discriminatory language based on religion.",
            " This text contains religuous epithets.",
            " This text includes religuously offensive content.",
            " This text features derogatory language about religion."
        ],
    ],
    "rte": [
        [" The premise entails the hypothesis."],
        [" The premise does not entail the hypothesis."]
    ],
    "cb": [
        [" The premise entails the hypothesis."],
        [" The premise does not entail the hypothesis."]
    ]
}

TASK2ARGS ={
    "sst2": {},
    "adv_sst2": {},
    "advmix_sst2": {},
    "sst5": {},
    "yelp2": {},
    "yelp5": {},
    "poem_sentiment": {},
    "yahoo_answers_topics": {},
    "emotion6": {},
    "agnews": {},
    "trec": {},
    "subjectivity": {},
    "boolq": {},
    "jigsaw": {},
    "hate_speech18": {},
}

# ["It is about World. "],
# ["It is about Sports. "],
# ["It is about Business. "],
# ["It is about Technology. "]